spring:
  application:
    name: gateway
  main:
    web-application-type: servlet
#    web-application-type: reactive
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-static
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products
              filters:
                - RewritePath=/products, /api/v1/products
#    gateway:
#      server:
#        webflux:
#          discovery:
#            locator:
#              enabled: true
#              lower-case-service-id: true
#         routes:
#           - id: product-static
#             uri: lb://PRODUCT-SERVICE
#             predicates:
#               - Path=/products
#             filters:
#               - name: CustomPath
#                 args:
#                   newPath: /api/v1/products

#           - id: product-static
#             uri: lb://PRODUCT-SERVICE
#             predicates:
#               - Path=/products
#             filters:
#               - RewritePath=/products, /api/v1/products
#           - id: product-dynamic
#             uri: lb://PRODUCT-SERVICE
#             predicates:
#               - Path=/products/**
#             filters:
#               - RewritePath=/products/(?<segment>.*), /api/v1/${segment}
           # if you want to filter you still have to do it manually
#           - id: product-root
#             uri: lb://PRODUCT-SERVICE
#             predicates:
#               - Path=/products/**
#             filters:
#              - RewritePath=/products/(?<segment>) , /api/v1/products/${segment}

             #      default-filters:
#        - StripPrefix=1
#     server:
#       webflux:
#         routes:
#           - id: product-root
#             uri: http://localhost:8081
#             predicates:
#               - Path=/products
#             filters:
#              - PrefixPath= /api/v1/
#           - id: product-based
#             uri: http://localhost:8081
#             predicates:
#               - Path=/products/**
#             filters:
##               - AddRequestHeader= key, value
##               - StripPrefix=1
##               - RemoveRequestHeader=key
#               - PrefixPath=/api/v1/
#               - RewritePath=/products/(?<segment>), products/${segment}
logging:
  level:
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
